import { PricingPlan } from "@/types";

export const pricingPlans: PricingPlan[] = [
  {
    name: "Starter",
    description: "For small teams getting started with business analytics.",
    price: 29,
    currency: "USD",
    interval: "month",
    featured: false,
    features: [
      "Up to 5 users",
      "3 data sources",
      "Standard dashboards",
      "Weekly email reports",
      "Community support",
      "API access",
    ],
    cta: "Start Free Trial",
  },
  {
    name: "Professional",
    description: "For growing teams that need deeper insights.",
    price: 99,
    currency: "USD",
    interval: "month",
    featured: true,
    features: [
      "Up to 25 users",
      "Unlimited data sources",
      "Custom dashboards",
      "Real-time updates",
      "AI-powered insights",
      "Priority support",
      "API access",
      "SSO integration",
    ],
    cta: "Start Free Trial",
  },
  {
    name: "Enterprise",
    description: "For organizations that need scale, security, and control.",
    price: 299,
    currency: "USD",
    interval: "month",
    featured: false,
    features: [
      "Unlimited users",
      "Unlimited data sources",
      "Advanced AI models",
      "Custom integrations",
      "Dedicated support",
      "SLA guarantee",
      "SSO + SCIM",
      "Audit logging",
      "Custom branding",
      "On-premise option",
    ],
    cta: "Contact Sales",
  },
];
